In [1]:
print("fuck u")

fuck u


In [4]:
!nvidia-smi


Sat Apr 22 14:22:02 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   64C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [7]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.0+cu118


In [10]:
#introduction to tensor
# creating tttensors


In [12]:
#scalar
scalar=torch.tensor(7)
scalar
# ->is a mylti dimensinal matric containing elements of a sung data type 

tensor(7)

In [15]:
scalar.ndim

0

In [17]:
scalar.item()
#get tensor back to int

7

In [19]:
#vector
vector=torch.tensor([7,7,73,3,])
vector

tensor([ 7,  7, 73,  3])

In [20]:
vector.shape

torch.Size([4])

In [22]:
#matrix
matrix=torch.tensor([[3,3,2,3],[3,3,3,3]])
matrix.shape

torch.Size([2, 4])

## random tensor
why random tensors
random tensors are importace bc the way neural networks learn is that that start with tensor full of random
random number->look at data-> update randome number->look at data

In [25]:
# create a random tenser
rd_tensor=torch.rand(3,4)
rd_tensor

tensor([[0.0443, 0.9684, 0.5917, 0.8279],
        [0.0128, 0.8372, 0.0517, 0.9914],
        [0.0446, 0.5451, 0.1130, 0.9700]])

In [27]:
image_rd=torch.rand(size=(224,224,3))#height withd color channel (rgb)
image_rd.shape,image_rd.ndim

(torch.Size([224, 224, 3]), 3)

In [29]:
zeros=torch.zeros(3,4)

In [31]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Tensor datatype

# float dtype=None-> float32 dtype float 16
? not right datatype-> check dtype
not right shape->tensor.shape
tensor.device

### manipulating tensor
operation include
addition,subraction, mutiplication element,divisons, matrix mutiplication


# finding min max,mean and sum


In [38]:
x= torch.arange(0.0,100.0,10)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [40]:
x.min(),x.max(),x.mean()

(tensor(0.), tensor(90.), tensor(45.))

In [41]:
# index of min
x.argmin(),x.argmax

(tensor(0), <function Tensor.argmax>)

In [43]:
x = torch.arange(1., 8.)
x, x.shape


(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [49]:
# Add an extra dimension
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [1]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # try changing dim to dim=1 and see what happens
x_stacked

NameError: ignored

## indexing 
ndexing with pytorch similar with Numoy

In [3]:
import torch as to
x=to.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [4]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [6]:
x[0][1]

tensor([4, 5, 6])

In [8]:
x[0][0][0]

tensor(1)

In [12]:
x[0][1:3][0:2]

tensor([[4, 5, 6],
        [7, 8, 9]])

##reproducity
in short
` start with random number -> tensor operations -> update randon -> again and again`

In [ ]:
# setup devoce agnostic code
